# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS }}

          # Options
          user: FallenDev
          template: classic
          base: activity, metadata
          base_indepth: yes
          config_timezone: America/New_York
          
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_limit: 12
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          
          plugin_activity: yes
          plugin_activity_days: 180
          plugin_activity_filter: all
          plugin_activity_limit: 5
          plugin_activity_load: 350
          plugin_activity_visibility: all
          
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming, data
          plugin_languages_colors: github
          plugin_languages_limit: 5
          plugin_languages_threshold: 0%
          plugin_languages_recent_categories: markup, programming, data
          plugin_languages_recent_days: 180
          plugin_languages_recent_load: 350
          plugin_languages_sections: most-used
          
          plugin_lines: yes
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: base
          plugin_lines_delay: 30
